spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://gj5HpH1i3ff6DJJ78NS8ydJ7s3eXOeE5@dpg-clsncjgcmk4c73cc3r0g-a/carpar_postgres_dadabase
    driverClassName: org.postgresql.Driver
    password: gj5HpH1i3ff6DJJ78NS8ydJ7s3eXOeE5
    username: carpar_postgres_dadabase_user
rsa:
  private-key: classpath:certificates/private.pem
  public-key: classpath:certificates/public.pem


